version: '3.1'
services:
  registry-server:
    image: thetinydev/registry:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - custom_network
networks:
  custom_network:
